### ISSUE TITLE
Previews are tiff

### ISSUE THREAD

**Issue by carusog** [patrickfatrick/TomorrowNightEighties#1]
Hi, previews are tiff, so not visible in the read me.

**Comment by patrickfatrick** [comment]
Hi, I see what you're saying. They were working before! Either way I replaced them with PNGs and they're showing up again. Thanks for letting me know!

**Comment by carusog** [comment]
It works now, thanks. :+1:

**Comment by patrickfatrick** [comment]
No problem!
